# run using:
# docker-compose rm ; docker-compose up --build
version: '3'
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 65535
services:
  dxgpu-db:
    container_name: dxgpu-db
    image: dxgpu-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    build:
      context: node-server/
      dockerfile: db.dockerfile

  dxgpu-app:
    container_name: dxgpu-node-server
    image: dxgpu-node-server
    environment:
      DB_HOST: dxgpu-db
      DB_READ_HOST: dxgpu-db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      INTERNAL_DOMAIN_NAME: dxgpu-node-server
      NODE_ENV: development
      SESSION_SECRET: superrandom
    build:
      context: node-server/
      dockerfile: app.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dxgpu-db
